[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.0.1"

# Description
title = "Ground Control"
description="Extension providing main framework interfaces and abstractions for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/UWRobotLearning/GroundControl"
category = "robotics"
keywords = ["kit", "robotics", "learning", "ai", "ground autonomy"]

[dependencies]
"omni.isaac.core" = {}
"omni.isaac.ml_archive" = {}
"omni.replicator.core" = {}

[python.pipapi]
requirements = [
    "numpy",
    "prettytable==3.3.0",
    "tensordict",
    "toml",
    "hidapi",
    "gymnasium==0.29.0",
    "trimesh"
]

modules = [
    "numpy",
    "prettytable",
    "tensordict",
    "toml",
    "hid",
    "gymnasium",
    "trimesh"
]

use_online_index=true

[[python.module]]
name = "omni.isaac.groundcontrol"
