seed: 42

# # not tuned
n_timesteps: !!float 1000000
policy: 'MlpPolicy'
learning_rate: !!float 3e-4
buffer_size: 50000
batch_size: 512
ent_coef: 0.1
train_freq: 32
gradient_steps: 32
gamma: 0.9999
tau: 0.01
learning_starts: 1000
use_sde: True
policy_kwargs: "dict(log_std_init=-3.0, net_arch=[128, 128, 128])"
device: "cuda:0"