[package]

# Note: Semantic Versioning is used: https://semver.org/
version = "0.1.0"

# Description
title = "Ground Control Assets"
description="Extension containing suite of environments for robot learning."
readme  = "docs/README.md"
repository = "https://github.com/UWRobotLearning/GroundControl"
category = "robotics"
keywords = ["kit", "robotics", "learning", "ai", "ground autonomy"]

[dependencies]
"omni.isaac.lab" = {}
"omni.isaac.lab_assets" = {}

[python.pipapi]
requirements = [
    "h5py",
    "tensorboard",
    "stable-baselines3>=2.1",
    "rl-games==1.6.1",
    "rsl-rl@git+https://github.com/leggedrobotics/rsl_rl.git",
    "skrl>=1.2.0"
]

modules = [
    "h5py",
    "tensorboard",
    "stable_baselines3",
    "rl_games",
    "rsl_rl",
    "skrl"
]

use_online_index=true

[[python.module]]
name = "omni.isaac.groundcontrol_assets"
